version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: git submodule update --init # needed for tests
      - run: python3 -m pip install --user tox

        # TODO use different versions of python
      - run: python3 -m tox


workflows:
  version: 2

  build_and_check:
    jobs:
      - build_and_test
