version: 2

jobs:
  build_and_check:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: git submodule update --init

      # TODO preserve apt cache..
      - run: sudo apt install python3-pip
      - run: python3 -m pip install --user tox

      - run: python3 -m pip install --user pytest
      - run: python3 -m pip install --user -e .
      - run: PYTHONPATH=src python3 -m pytest -s tests/test_kobo.py
      # TODO fix tox...
      # - run: python3 -m tox

workflows:
  version: 2

  build_and_check:
    jobs:
      - build_and_check
